print('hello all, greetings of the day!!!')

In [7]:
a=10
b=67
c=11
d=a+b+c
l=a-b+c
print(l)
print(d)

-46
88


### isdigit()


In [1]:
print(help(str.isdigit))


Help on method_descriptor:

isdigit(self, /) unbound builtins.str method
    Return True if the string is a digit string, False otherwise.

    A string is a digit string if all characters in the string are digits and there
    is at least one character in the string.

None


In [5]:
a='3489abc'


In [6]:
a.isdigit()

False

#### isallnum()


In [8]:
a.isalnum()

True

In [ ]:
a= 'proGram23'

In [9]:
a.isalnum()

True

#### isalpha()


In [10]:
a="43pro"

In [11]:
a.isalpha()

False

#### isspace

In [12]:
print(help(str.isspace))

Help on method_descriptor:

isspace(self, /) unbound builtins.str method
    Return True if the string is a whitespace string, False otherwise.

    A string is whitespace if all characters in the string are whitespace and there
    is at least one character in the string.

None


In [13]:
a="   "
a.isspace()

True

In [14]:
b="    aaaaaac"
b.isspace()

False

#### istitle()

In [16]:
print(help(str.istitle))


Help on method_descriptor:

istitle(self, /) unbound builtins.str method
    Return True if the string is a title-cased string, False otherwise.

    In a title-cased string, upper- and title-case characters may only
    follow uncased characters and lowercase characters only cased ones.

None


In [17]:
a="Ipe"
a.istitle()

True

In [18]:
a="pIo"
a.istitle()

False

In [19]:
chr(67)
chr(65)

'A'

In [21]:
print(chr(67))
print(chr(65))

C
A


#### format()

In [24]:
print(help(str.format))

Help on method_descriptor:

format(self, /, *args, **kwargs) unbound builtins.str method
    Return a formatted version of the string, using substitutions from args and kwargs.
    The substitutions are identified by braces ('{' and '}').

None


In [25]:
text = "my name is saivamshi , my age is 889"
print(text)

my name is saivamshi , my age is 889


In [26]:
text = "my name is {},my age is {}"
text.format("sai","55")

'my name is sai,my age is 55'

'my name is ss,my age is rsra'

In [31]:
text.format("ss "," ""rsra")

'my name is ss ,my age is  rsra'

In [32]:
text = "my name is {0},my age is {1}"
text.format("sai","55")

'my name is sai,my age is 55'

In [38]:
text = "my name is {name},my age is {age}"
text.format(age =5, name = "sai")

'my name is sai,my age is 5'

In [3]:
li = ["how","keep","python"]
for x in li:
    print(x)

how
keep
python


In [4]:
li = ["how","keep","python"]
for y in li:
    print(y)

how
keep
python


In [5]:
x=0
while (x <40):
    x=x+1
    print("hello world")

hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world


In [6]:
for i in range (1,21):
    if(i %3 ==0):
        continue
    print(i)


1
2
4
5
7
8
10
11
13
14
16
17
19
20


In [14]:
count = 0
for i in range (1,50):
    if(i %2 ==0):
        count +=1
        print(count)
        print(i)


1
2
2
4
3
6
4
8
5
10
6
12
7
14
8
16
9
18
10
20
11
22
12
24
13
26
14
28
15
30
16
32
17
34
18
36
19
38
20
40
21
42
22
44
23
46
24
48


In [16]:
total = 0 
for i in range(10):
    num = int(input())
    if num >0:
        total = total + num
print("total sun of the positive numbers is:", total)

 56
 8888
 77
 


ValueError: invalid literal for int() with base 10: ''

In [26]:
num =51
while True:
    if num % 7==0:
        print(num)
        break
    num+=1

56


In [32]:
sum=0
while True:
    n=int(input(   ))
    if n == 0:
        break
    else:
        sum=sum+n
print("sum",sum)


 2
 3
 3
 4
 0


sum 12


In [39]:
row =5
for i in range(row):
    for j in range(row):
        if i == j:
            print(" ",end=" ")
            continue
        print("*",end =" ")
    print()

  * * * * 
*   * * * 
* *   * * 
* * *   * 
* * * *   


In [1]:
import numpy as np

In [5]:
np.array([23,47,90,53])

array([23, 47, 90, 53])

In [6]:
arr = np.array([10,20,30,40])


In [7]:
arr

array([10, 20, 30, 40])

In [8]:
l = [35,45,55,66]

In [9]:
np.array(l)

array([35, 45, 55, 66])

In [10]:
type(arr)

numpy.ndarray

In [12]:
# memory address of an array
arr.data

In [13]:
#data type of an array 

In [14]:
arr.dtype

dtype('int64')

In [15]:
# size of any array
arr.size

4

In [16]:
#dimentions of an array 
arr.ndim

1

In [17]:
arr

array([10, 20, 30, 40])

In [18]:
# bytes consumed by one elements
arr

array([10, 20, 30, 40])

In [20]:
arr.itemsize

8

In [21]:
# total bytes consumed by an array
arr.nbytes

32

In [22]:
#lenght of an array 
len (arr)

4

In [23]:
arr

array([10, 20, 30, 40])

In [24]:
# convert integer array into float 
arr.astype(float)

array([10., 20., 30., 40.])

In [25]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [26]:
np.arange(1,2000,5)

array([   1,    6,   11,   16,   21,   26,   31,   36,   41,   46,   51,
         56,   61,   66,   71,   76,   81,   86,   91,   96,  101,  106,
        111,  116,  121,  126,  131,  136,  141,  146,  151,  156,  161,
        166,  171,  176,  181,  186,  191,  196,  201,  206,  211,  216,
        221,  226,  231,  236,  241,  246,  251,  256,  261,  266,  271,
        276,  281,  286,  291,  296,  301,  306,  311,  316,  321,  326,
        331,  336,  341,  346,  351,  356,  361,  366,  371,  376,  381,
        386,  391,  396,  401,  406,  411,  416,  421,  426,  431,  436,
        441,  446,  451,  456,  461,  466,  471,  476,  481,  486,  491,
        496,  501,  506,  511,  516,  521,  526,  531,  536,  541,  546,
        551,  556,  561,  566,  571,  576,  581,  586,  591,  596,  601,
        606,  611,  616,  621,  626,  631,  636,  641,  646,  651,  656,
        661,  666,  671,  676,  681,  686,  691,  696,  701,  706,  711,
        716,  721,  726,  731,  736,  741,  746,  7

In [27]:
# generate evenly space number b/w 1-20
np. arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [28]:
np. arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [30]:
np. arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

#### zeros()

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### eye()

In [34]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

### diag()

In [35]:
np.diag([10,20,30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

### missing values in an array


In [1]:
import numpy as np

In [2]:
a = np.array([10,np.nan,34,np.nan])

In [3]:
a

array([10., nan, 34., nan])

#### isnan()
-searches for an missing values and return boolean array

In [6]:
np.isnan(a)

array([False,  True, False,  True])

In [8]:
b[3][4]=1,2,3,3,44,5,5,5,55,5,55,


NameError: name 'b' is not defined

In [9]:
b

NameError: name 'b' is not defined

In [14]:
a = np.array([12,np.nan,34],[np.nan,56],[1,np,nan,23])

NameError: name 'nan' is not defined

In [13]:
a

array([10., nan, 34., nan])